"use client";
import React from "react";
import {Skeleton} from "./ui/skeleton";
import {Ellipsis,XIcon} from "lucide-react";
import Image from "next/image";
import {motion} from "framer-motion";

import i1 from "@/assets/01.jpg";
import i2 from "@/assets/2.jpg";
import i3 from "@/assets/3.jpg";
import gen3 from "@/assets/gen3.jpg";

// Reusable Card Component
function Card({src,alt}) {
    return (
        <div className="py-4 border shadow-sm rounded-md">
            <div className="px-2.5 flex justify-between items-center">
                <div className="flex items-center gap-2">
                    <Skeleton className="h-9 w-9 rounded-full" />
                    <Skeleton className="h-4 w-[100px]" />
                </div>
                <div className="flex gap-1.5">
                    <Ellipsis className="h-5 w-5 text-neutral-600" />
                    <XIcon className="h-5 w-5 text-neutral-600" />
                </div>
            </div>
            <div className="space-y-1.5 px-2.5 my-3">
                <Skeleton className="h-4 w-[220px]" />
                <Skeleton className="h-4 w-[170px]" />
            </div>
            <Image src={src} height={350} width={300} alt={alt} />
            <div className="space-y-1.5 px-2.5 mt-3">
                <Skeleton className="h-5 w-[200px]" />
            </div>
        </div>
    );
}

export default function Examples() {
    const images = [i1,i2,i3,gen3,i1,i2,i3,gen3];

    return (
        <section className="py-14 md:py-18 xl:py-24">
            <div className="flex items-center flex-col">
                <h1 className="tag font-header text-lg mb-2">Examples</h1>
                <p className="font-bold text-3xl lg:text-5xl tracking-tight font-header">
                    All generated by our AI
                </p>
            </div>
            <main className="flex overflow-hidden mt-20">
                {/* Forward Marquee */}
                <motion.div
                    animate={{translateX: '-50%'}}
                    transition={{duration: 10,repeat: Infinity,ease: "linear"}}
                    className="flex justify-center gap-14 flex-none pr-14">
                    {images.map((img,idx) => (
                        <Card src={img} alt={`Special offer for selling watches ads ${idx + 1}`} key={idx} />
                    ))}
                </motion.div>
            </main>
        </section>
    )
}
