import {examples} from '@/assets/assets'
import React from 'react'
import {Skeleton} from './ui/skeleton'
import {Ellipsis,XIcon} from 'lucide-react'
import Image from 'next/image'

const Examples = () => {
    return (
        <section className='py-14 md:py-18 bg-gray-50 xl:py-24'>
            <div className="flex items-center flex-col">
                <h1 className='tag font-header text-lg mb-2'>Examples</h1>
                <p className='font-bold text-3xl lg:text-5xl tracking-tight font-header'>All generated by our AI</p>
            </div>
            <main className='grid grid-cols-2 mt-14 md:grid-cols-3 xl:grid-cols-4 gap-16 '>
                {
                    examples.map((example,index) => (
                        <div key={index} className='py-4 border shadow-sm rounded-md' >
                            <main>
                                <div className='px-2.5 flex justify-between items-center' >
                                    <div className='flex items-center gap-2'>
                                        <Skeleton className="h-9 w-9 rounded-full" />
                                        <Skeleton className="h-4 w-[100px]" />
                                    </div>
                                    <div className='flex gap-1.5'>
                                        <Ellipsis className='h-5 w-5 text-neutral-600' />
                                        <XIcon className='h-5 w-5 text-neutral-600' />
                                    </div>
                                </div>
                                <div className="space-y-1.5 px-2.5 my-3">
                                    <Skeleton className="h-4 w-[220px]" />
                                    <Skeleton className="h-4 w-[170px]" />
                                </div>
                                <Image src={example.image} height={350} width={300} alt={example.alt} />
                                <div className="space-y-1.5 px-2.5 mt-3">
                                    <Skeleton className="h-5 w-[200px]" />
                                </div>

                            </main>

                        </div>
                    ))
                }
            </main>

        </section>
    )
}

export default Examples
